# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3a3e999ac30504c48ae5e02f65633fecd0b8e2039efbf710d89e18182976b282cd07631258ac25fee8bfe9f54e6baaec8a6fc5b5ef24f0760134fa33030cb7

test:
  secret_key_base: 9c1e9eb28a25d7db4bd6691e57a8d8fca31af49b96a73f13e20ea3303df683296e8258744a336e6fcf01bb50151c05fa06cfd8696e9d831b64b40369b9969826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
